---
name: generalTicket
version: 3
namespace: CoreTx
description: general ticket info for eventchain
proto: protocol.proto
type_urls:
  ec:s:general_ticket: ForgeAbi.GeneralTicket
pipeline: protocol.yml
sources: []

